name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: go mod tidy
        run: go mod tidy -diff
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v ./...
